services:
  db:
    image: postgis/postgis:16-3.4-alpine
    container_name: flushfinder-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: washroom
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d washroom"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pg_data:
