[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn src.main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONPATH = "src"
